export const CommonConstants = {
    SYSTEM: 'System',
    MANUAL: 'Manual',
    DISCOUNT_JUSTIFICATION: 'Discount Justification',
    CANCEL: 'Cancel',
    APPLY: 'Apply',
    CLOSE: 'Close',
    ACTIVE: 'Active',
    INACTIVE: 'Inactive',
    ACTIVATE: 'Activate',
    CONTENTS_FETCH: 'Content is being fetched',
    ITEMS_SHIMMER: 'Item details',
    SETKEY: 'Items',
    STICKY_HEADER: 'Sticky Header',
    YES: 'Yes',
    NO: 'No',
    MANUAL_EXCEPTION: 'ManualExceptions'
};
export const DEFAULT_PAGE_SIZE = 10;
export const SORT_TYPE = {
    ASC: 'asc',
    DESC: 'desc'
};
export const MONTH_NAMES_FULL = [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December'
];
export const MONTH_NAMES_SHORT = [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec'
];
export const COMMON_LOCALIZATION_CONSTANTS = {
    SAVE: { id: 'Core.Common.Save', defaultMessage: 'Save' },
    CANCEL: { id: 'Core.Common.Cancel', defaultMessage: 'Cancel' },
    NEXT: { id: 'Core.Common.Next', defaultMessage: 'Next' },
    PREVIOUS: { id: 'Core.Common.Previous', defaultMessage: 'Previous' },
    REJECT: { id: 'Core.Common.Reject', defaultMessage: 'Reject' },
    SUBMIT: { id: 'Core.Common.Submit', defaultMessage: 'Submit' },
    SEARCH: { id: 'Core.Common.Search', defaultMessage: 'Search' },
    EDIT: { id: 'Core.Common.Edit', defaultMessage: 'Edit' },
    REMOVE: { id: 'Core.Common.Remove', defaultMessage: 'Remove' },
    REMOVE_ALL: { id: 'Core.Common.RemoveAll', defaultMessage: 'Remove All' },
    DELETE: { id: 'Core.Common.Delete', defaultMessage: 'Delete' },
    DELETE_ALL: { id: 'Core.Common.DeleteAll', defaultMessage: 'Delete All' },
    CLEAR: { id: 'Core.Common.Clear', defaultMessage: 'Clear' },
    DISCARD: { id: 'Core.Common.Discard', defaultMessage: 'Discard' },
    FILTERS: { id: 'Core.Common.Filters', defaultMessage: 'Filters' },
    BROWSE: { id: 'Core.Common.Browse', defaultMessage: 'Browse' },
    SIGN_OUT: { id: 'Core.Common.SignOut', defaultMessage: 'Sign Out' },
    EXPORT: { id: 'Core.Common.Export', defaultMessage: 'Export' },
    SORT: { id: 'Core.Common.Sort', defaultMessage: 'Sort' },
    SORT_BY: { id: 'Core.Common.SortBy', defaultMessage: 'Sort By' },
    DESCENDING: { id: 'Core.Common.Descending', defaultMessage: 'Descending' },
    ASCENDING: { id: 'Core.Common.Ascending', defaultMessage: 'Ascending' },
    SORT_A_TO_Z: { id: 'Core.Common.SortAToZ', defaultMessage: 'Sort A To Z' },
    SORT_Z_TO_A: { id: 'Core.Common.SORTZToA', defaultMessage: 'SORT Z To A' },
    FIELDS: { id: 'Core.Common.Fields', defaultMessage: 'Fields' },
    CONFIRMATION: { id: 'Core.Common.Confirmation', defaultMessage: 'Confirmation' },
    YES: { id: 'Core.Common.Yes', defaultMessage: 'Yes' },
    NO: { id: 'Core.Common.No', defaultMessage: 'No' },
    SELECT_ALL: { id: 'Core.Common.SelectAll', defaultMessage: 'Select All' },
    NOT_SELECTED: { id: 'Core.Common.NotSelected', defaultMessage: 'Not Selected' },
    SELECTED: { id: 'Core.Common.Selected', defaultMessage: 'Selected' },
    EXPANDED: { id: 'Core.Common.Expanded', defaultMessage: 'Expanded' },
    COLLAPSED: { id: 'Core.Common.Collapsed', defaultMessage: 'Collapsed' },
    REQUIRED_FIELD: { id: 'Core.Common.RequiredField', defaultMessage: 'Required Field' },
    INVALID_VALUE: { id: 'Core.Common.InvalidValue', defaultMessage: 'Invalid Value' },
    JAN: { id: 'Core.Common.Months.Jan', defaultMessage: 'Jan' },
    JANUARY: { id: 'Core.Common.Months.January', defaultMessage: 'January' },
    FEB: { id: 'Core.Common.Months.Feb', defaultMessage: 'Feb' },
    FEBRUARY: { id: 'Core.Common.Months.February', defaultMessage: 'February' },
    MAR: { id: 'Core.Common.Months.Mar', defaultMessage: 'Mar' },
    MARCH: { id: 'Core.Common.Months.March', defaultMessage: 'March' },
    APR: { id: 'Core.Common.Months.Apr', defaultMessage: 'Apr' },
    APRIL: { id: 'Core.Common.Months.April', defaultMessage: 'April' },
    MAY: { id: 'Core.Common.Months.May', defaultMessage: 'May' },
    JUN: { id: 'Core.Common.Months.Jun', defaultMessage: 'Jun' },
    JUNE: { id: 'Core.Common.Months.June', defaultMessage: 'June' },
    JUL: { id: 'Core.Common.Months.Jul', defaultMessage: 'Jul' },
    JULY: { id: 'Core.Common.Months.July', defaultMessage: 'July' },
    AUG: { id: 'Core.Common.Months.Aug', defaultMessage: 'Aug' },
    AUGUST: { id: 'Core.Common.Months.August', defaultMessage: 'August' },
    SEP: { id: 'Core.Common.Months.Sep', defaultMessage: 'Sep' },
    SEPTEMBER: { id: 'Core.Common.Months.September', defaultMessage: 'September' },
    OCT: { id: 'Core.Common.Months.Oct', defaultMessage: 'Oct' },
    OCTOBER: { id: 'Core.Common.Months.October', defaultMessage: 'October' },
    NOV: { id: 'Core.Common.Months.Nov', defaultMessage: 'Nov' },
    NOVEMBER: { id: 'Core.Common.Months.November', defaultMessage: 'November' },
    DEC: { id: 'Core.Common.Months.Dec', defaultMessage: 'Dec' },
    DECEMBER: { id: 'Core.Common.Months.December', defaultMessage: 'December' }
};
