export const CommonConstants = {
    SYSTEM: 'System',
    MANUAL: 'Manual',
    DISCOUNT_JUSTIFICATION: 'Discount Justification',
    CANCEL: 'Cancel',
    APPLY: 'Apply',
    CLOSE: 'Close',
    ACTIVE: 'Active',
    INACTIVE: 'Inactive',
    ACTIVATE: 'Activate',
    CONTENTS_FETCH: 'Content is being fetched',
    ITEMS_SHIMMER: 'Item details',
    SETKEY: 'Items',
    STICKY_HEADER: 'Sticky Header',
    YES: 'Yes',
    NO: 'No',
    MANUAL_EXCEPTION: 'ManualExceptions'
};
export const TWELVE_COLUMN_CLASS = 'ms-Grid-col ms-sm12 ms-md12 ms-lg12 ms-xl12';
export const DEFAULT_PAGE_SIZE = 10;
export const SORT_TYPE = {
    ASC: 'asc',
    DESC: 'desc'
};
export const MONTH_NAMES_FULL = [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December'
];
export const MONTH_NAMES_SHORT = [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec'
];
export const COMMON_LOCALIZATION_STRINGS = {
    SAVE: { id: 'Common_Save', defaultMessage: 'Save' },
    CANCEL: { id: 'Common_Cancel', defaultMessage: 'Cancel' },
    NEXT: { id: 'Common_Next', defaultMessage: 'Next' },
    PREVIOUS: { id: 'Common_Previous', defaultMessage: 'Previous' },
    REJECT: { id: 'Common_Reject', defaultMessage: 'Reject' },
    SUBMIT: { id: 'Common_Submit', defaultMessage: 'Submit' },
    SEARCH: { id: 'Common_Search', defaultMessage: 'Search' },
    EDIT: { id: 'Common_Edit', defaultMessage: 'Edit' },
    REMOVE: { id: 'Common_Remove', defaultMessage: 'Remove' },
    REMOVE_ALL: { id: 'Common_RemoveAll', defaultMessage: 'Remove All' },
    DELETE: { id: 'Common_Delete', defaultMessage: 'Delete' },
    DELETE_ALL: { id: 'Common_DeleteAll', defaultMessage: 'Delete All' },
    CLEAR: { id: 'Common_Clear', defaultMessage: 'Clear' },
    DISCARD: { id: 'Common_Discard', defaultMessage: 'Discard' },
    FILTERS: { id: 'Common_Filters', defaultMessage: 'Filters' },
    BROWSE: { id: 'Common_Browse', defaultMessage: 'Browse' },
    SIGN_OUT: { id: 'Common_SignOut', defaultMessage: 'Sign Out' },
    EXPORT: { id: 'Common_Export', defaultMessage: 'Export' },
    SORT: { id: 'Common_Sort', defaultMessage: 'Sort' },
    SORT_BY: { id: 'Common_SortBy', defaultMessage: 'Sort By' },
    DESCENDING: { id: 'Common_Descending', defaultMessage: 'Descending' },
    ASCENDING: { id: 'Common_Ascending', defaultMessage: 'Ascending' },
    SORT_A_TO_Z: { id: 'Common_SortAToZ', defaultMessage: 'Sort A To Z' },
    SORT_Z_TO_A: { id: 'Common_SORTZToA', defaultMessage: 'SORT Z To A' },
    FIELDS: { id: 'Common_Fields', defaultMessage: 'Fields' },
    CONFIRMATION: { id: 'Common_Confirmation', defaultMessage: 'Confirmation' },
    YES: { id: 'Common_Yes', defaultMessage: 'Yes' },
    NO: { id: 'Common_No', defaultMessage: 'No' },
    SELECT_ALL: { id: 'Common_SelectAll', defaultMessage: 'Select All' },
    NOT_SELECTED: { id: 'Common_NotSelected', defaultMessage: 'Not Selected' },
    SELECTED: { id: 'Common_Selected', defaultMessage: 'Selected' },
    EXPANDED: { id: 'Common_Expanded', defaultMessage: 'Expanded' },
    COLLAPSED: { id: 'Common_Collapsed', defaultMessage: 'Collapsed' },
    REQUIRED_FIELD: { id: 'Common_RequiredField', defaultMessage: 'Required Field' },
    INVALID_VALUE: { id: 'Common_InvalidValue', defaultMessage: 'Invalid Value' },
    ACTION: { id: 'Common_Action', defaultMessage: 'Action' },
    JAN: { id: 'Common_Months_Jan', defaultMessage: 'Jan' },
    JANUARY: { id: 'Common_Months_January', defaultMessage: 'January' },
    FEB: { id: 'Common_Months_Feb', defaultMessage: 'Feb' },
    FEBRUARY: { id: 'Common_Months_February', defaultMessage: 'February' },
    MAR: { id: 'Common_Months_Mar', defaultMessage: 'Mar' },
    MARCH: { id: 'Common_Months_March', defaultMessage: 'March' },
    APR: { id: 'Common_Months_Apr', defaultMessage: 'Apr' },
    APRIL: { id: 'Common_Months_April', defaultMessage: 'April' },
    MAY: { id: 'Common_Months_May', defaultMessage: 'May' },
    JUN: { id: 'Common_Months_Jun', defaultMessage: 'Jun' },
    JUNE: { id: 'Common_Months_June', defaultMessage: 'June' },
    JUL: { id: 'Common_Months_Jul', defaultMessage: 'Jul' },
    JULY: { id: 'Common_Months_July', defaultMessage: 'July' },
    AUG: { id: 'Common_Months_Aug', defaultMessage: 'Aug' },
    AUGUST: { id: 'Common_Months_August', defaultMessage: 'August' },
    SEP: { id: 'Common_Months_Sep', defaultMessage: 'Sep' },
    SEPTEMBER: { id: 'Common_Months_September', defaultMessage: 'September' },
    OCT: { id: 'Common_Months_Oct', defaultMessage: 'Oct' },
    OCTOBER: { id: 'Common_Months_October', defaultMessage: 'October' },
    NOV: { id: 'Common_Months_Nov', defaultMessage: 'Nov' },
    NOVEMBER: { id: 'Common_Months_November', defaultMessage: 'November' },
    DEC: { id: 'Common_Months_Dec', defaultMessage: 'Dec' },
    DECEMBER: { id: 'Common_Months_December', defaultMessage: 'December' },
    NO_RESULTS_FOUND: { id: 'Common_NoResultsFound', defaultMessage: 'No Results Found' },
    LOADING: { id: 'Common_Loading', defaultMessage: 'Loading' },
    SHOWING_TOP: { id: 'Common_ShowingTop', defaultMessage: 'December' },
    RESULTS: { id: 'Common_Results', defaultMessage: 'December' },
    ALL_RESULTS: { id: 'Common_AllResults', defaultMessage: 'December' },
    SHOW_MORE: { id: 'Common_ShowMore', defaultMessage: 'December' },
    SUGGESTED_RESULTS: { id: 'Common_SuggestedResults', defaultMessage: 'December' }
};
